export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';
export const MOVIE_LIST_RESET = 'MOVIE_LIST_RESET';

export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST';
export const MOVIE_DETAIL_SUCCESS = 'MOVIE_DETAIL_SUCCESS';
export const MOVIE_DETAIL_FAIL = 'MOVIE_DETAIL_FAIL';
export const MOVIE_DETAIL_RESET = 'MOVIE_DETAIL_RESET';

export const MOVIE_CREATE_REQUEST = 'MOVIE_CREATE_REQUEST';
export const MOVIE_CREATE_SUCCESS = 'MOVIE_CREATE_SUCCESS';
export const MOVIE_CREATE_FAIL = 'MOVIE_CREATE_FAIL';
export const MOVIE_CREATE_RESET = 'MOVIE_CREATE_RESET';

export const EP_LIST_REQUEST = 'EP_LIST_REQUEST';
export const EP_LIST_SUCCESS = 'EP_LIST_SUCCESS';
export const EP_LIST_FAIL = 'EP_LIST_FAIL';
export const EP_LIST_RESET = 'EP_LIST_RESET';

export const EP_CREATE_REQUEST = 'EP_CREATE_REQUEST';
export const EP_CREATE_SUCCESS = 'EP_CREATE_SUCCESS';
export const EP_CREATE_FAIL = 'EP_CREATE_FAIL';
export const EP_CREATE_RESET = 'EP_CREATE_RESET';

export const EP_UPDATE_REQUEST = 'EP_UPDATE_REQUEST';
export const EP_UPDATE_SUCCESS = 'EP_UPDATE_SUCCESS';
export const EP_UPDATE_FAIL = 'EP_UPDATE_FAIL';
export const EP_UPDATE_RESET = 'EP_UPDATE_RESET';

export const EP_DELETE_REQUEST = 'EP_DELETE_REQUEST';
export const EP_DELETE_SUCCESS = 'EP_DELETE_SUCCESS';
export const EP_DELETE_FAIL = 'EP_DELETE_FAIL';
export const EP_DELETE_RESET = 'EP_DELETE_RESET';

export const DESC_DELETE_REQUEST = 'DESC_DELETE_REQUEST';
export const DESC_DELETE_SUCCESS = 'DESC_DELETE_SUCCESS';
export const DESC_DELETE_FAIL = 'DESC_DELETE_FAIL';
export const DESC_DELETE_RESET = 'DESC_DELETE_RESET';

export const DESC_LIST_REQUEST = 'DESC_LIST_REQUEST';
export const DESC_LIST_SUCCESS = 'DESC_LIST_SUCCESS';
export const DESC_LIST_FAIL = 'DESC_LIST_FAIL';
export const DESC_LIST_RESET = 'DESC_LIST_RESET';

export const DESC_CREATE_REQUEST = 'DESC_CREATE_REQUEST';
export const DESC_CREATE_SUCCESS = 'DESC_CREATE_SUCCESS';
export const DESC_CREATE_FAIL = 'DESC_CREATE_FAIL';
export const DESC_CREATE_RESET = 'DESC_CREATE_RESET';

export const DESC_UPDATE_REQUEST = 'DESC_UPDATE_REQUEST';
export const DESC_UPDATE_SUCCESS = 'DESC_UPDATE_SUCCESS';
export const DESC_UPDATE_FAIL = 'DESC_UPDATE_FAIL';
export const DESC_UPDATE_RESET = 'DESC_UPDATE_RESET';
